// Generated by GPT4

export default function getDateFromEpoch(epoch: any) {
  const date = new Date(epoch); // convert epoch to milliseconds
  const today = new Date();
  const yesterday = new Date(today.getTime() - 1000 * 60 * 60 * 24);

  // set the time to 00:00:00 for comparison
  today.setHours(0, 0, 0, 0);
  date.setHours(0, 0, 0, 0);
  yesterday.setHours(0, 0, 0, 0);

  const diffInDays = Math.floor(
    ((today as any) - (date as any)) / (1000 * 60 * 60 * 24)
  );
  const dayNames = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];

  if (diffInDays === 0) {
    return "Today";
  } else if (diffInDays === 1) {
    return "Yesterday";
  } else if (diffInDays < 7) {
    return dayNames[date.getDay()];
  } else {
    return false;
  }
}
