-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."blocks" add column "is_locked" boolean
--  not null default 'false';
